add Tp-Link WRT3600-v1, Tp-Link 1043ND-v4, Linksys WRT3200ACM-EU
openwisp/openwisp-firmware-upgrader pull request #113
Opened 2020-12-04 02:51 UTC by mikysal78

2020-12-15 02:13 UTC, nemesisdesign reviewed
@mikysal78 looks good, once you have tested these let me know so I can merge.

2020-12-20 16:35 UTC, mikysal78 commented
test on device 1043nd-v4 .... Device model and image model do not match
I testing upload manual the new firmware and continue with Device model and image model do not match

2021-02-03 14:54 UTC, nemesisdesign requested changes

2021-02-03 14:54 UTC, nemesisdesign commented on openwisp_firmware_upgrader/hardware.py
> +                'openwrt-ipq806x-generic-tplink_c2600-squashfs-sysupgrade.bin',
`openwrt` all'inizio della stringa va rimosso

2021-02-03 14:54 UTC, nemesisdesign commented on openwisp_firmware_upgrader/hardware.py
> +                'openwrt-ipq806x-generic-tplink_c2600-squashfs-sysupgrade.bin',
vale anche per le altre occorrenze

2021-02-04 20:56 UTC, closed without merging