[cleanup] Re-generated sample app migrations #119
openwisp/openwisp-firmware-upgrader pull request #124
Opened 2021-03-12 15:25 UTC by codesankalp

Regenerated all migrations except data migration.

Closes #119

2021-03-12 15:43 UTC, codesankalp commented
@nemesisdesign The tests and QA-checks are passing locally. I have attached some images regarding this:

![image](https://user-images.githubusercontent.com/56037184/110962199-b4585700-8376-11eb-80b1-dc656546260a.png)

![image](https://user-images.githubusercontent.com/56037184/110962266-c9cd8100-8376-11eb-8f74-2917c383cb65.png)

![image](https://user-images.githubusercontent.com/56037184/110962353-e5388c00-8376-11eb-801f-6ca1bc761f4b.png)

2021-03-12 17:47 UTC, nemesisdesign commented
@atb00ker @pandafy @devkapilbansal did we have this problem of the build failing because of EULA acceptance somewhere else right, did we? If yes, how did we solve it?

2021-03-12 17:50 UTC, devkapilbansal commented
> @atb00ker @pandafy @devkapilbansal did we have this problem of the build failing because of EULA acceptance somewhere else right, did we? If yes, how did we solve it?

Yes this problem arises when mysql was updated.

@codesankalp consider removing `sudo apt-get upgrade` from here
https://github.com/openwisp/openwisp-firmware-upgrader/blob/6c01c1ec2b224789c1c1a1fb37ab1adf4f2189af/.github/workflows/ci.yml#L39

2021-03-12 22:15 UTC, nemesisdesign requested changes
Avoid changing lines which call specific functions from swapper or calls to dynamic data structures, see below.

2021-03-12 22:15 UTC, nemesisdesign commented on tests/openwisp2/sample_firmware_upgrader/migrations/0001_initial.py
> +                        ],
this line should not be changed

2021-03-12 22:15 UTC, nemesisdesign commented on tests/openwisp2/sample_firmware_upgrader/migrations/0001_initial.py
> +                        to='sample_firmware_upgrader.build',
same here

2021-03-12 22:15 UTC, nemesisdesign commented on tests/openwisp2/sample_firmware_upgrader/migrations/0001_initial.py
> +                        to='sample_firmware_upgrader.batchupgradeoperation',
same here

2021-03-12 22:15 UTC, nemesisdesign commented on tests/openwisp2/sample_firmware_upgrader/migrations/0001_initial.py
> -                        to=swapper.get_model_name('config', 'Device'),
same here, applies to all other occurrences

2021-03-16 11:12 UTC, devkapilbansal requested changes
@codesankalp Looks good, just one minor change

2021-03-16 11:12 UTC, devkapilbansal commented on tests/openwisp2/sample_firmware_upgrader/migrations/0001_initial.py
> +        ('openwisp_users', '0011_user_first_name_150_max_length'),
@codesankalp can we change this dependency with AUTH_USER_MODEL?
```suggestion
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
```

2021-03-16 19:43 UTC, nemesisdesign approved these changes

2021-03-16 19:43 UTC, nemesisdesign commented
Thanks @codesankalp @devkapilbansal :+1:

2021-03-16 19:44 UTC, merged