[enhancement] Registered menu groups #141
openwisp/openwisp-firmware-upgrader pull request #144
Opened 2021-07-24 05:39 UTC by niteshsinha17

Changes
Registered  Build, Category, and BatchUpgradeOperation models in a group name Firmware at position 100.

Checklist
 [x] I have read the contributing guidelines.
 [x] I have manually tested the proposed changes.
 [x] I have written new test cases to avoid regressions. (if necessary)
 [x] I have updated the documentation. (e.g. README.rst)

closes #141

2021-07-29 00:43 UTC, nemesisdesign requested changes
great!

Can you use the icon of a system on chip for the main group icon?

Something like:

- https://www.flaticon.com/free-icon/computer-cpu_63990
- https://www.flaticon.com/free-icon/chip_2948358

2021-07-29 00:43 UTC, nemesisdesign commented on openwisp_firmware_upgrader/apps.py
> +                        'label': _('Mass Upgrade Operation'),
Operation > Operations

2021-07-29 14:37 UTC, niteshsinha17 commented
changed icon
![image](https://user-images.githubusercontent.com/42765292/127511694-e5882048-cac0-478a-84d8-1df9f2ec91b8.png)

2021-07-29 18:20 UTC, nemesisdesign submitted a review, later dismissed

2021-08-01 16:40 UTC, nemesisdesign approved these changes

2021-08-01 16:41 UTC, merged