[feature] REST API is missing endpoints for DeviceFirmware #206
openwisp/openwisp-firmware-upgrader pull request #229
Opened 2023-04-04 21:27 UTC by tspare

[feature] REST API is missing endpoints for DeviceFirmware #206

The code adds three endpoints:

1.  upgrade-operation/ - List all the upgrade operation in the system
2.  upgrade-operation/<id>/ - Display detail of a particular upgrade id
3.  device/<id>/upgrade-operation/ - return a list of upgrade-operation ids for a gven device id

2023-04-04 22:55 UTC, nemesisdesign requested changes
Thanks for contributing!

The main requirement of the feature is not satisfied:

- CRUD operations of DeviceFirmware objects, eg: /api/v1/firmware upgrader/device/[id]/firmware/ 
  When a device firmwre is created or changed (which creates an upgrade operation) we should return the upgrade operation ID to allow clients to check the state of the upgrade

We will need to add tests and docs (add these endpoints to the README).

2023-04-10 21:38 UTC, tspare commented
> Thanks for contributing!
> 
> The main requirement of the feature is not satisfied:
> 
>     * CRUD operations of DeviceFirmware objects, eg: /api/v1/firmware upgrader/device/[id]/firmware/
>       When a device firmwre is created or changed (which creates an upgrade operation) we should return the upgrade operation ID to allow clients to check the state of the upgrade
> 
> 
> We will need to add tests and docs (add these endpoints to the README).

I updated the code to add the changes.  However, I am not sure if you want the upgrade operation to be saved in to the DeviceFirmware model or just return it as a separate field as part of the PUT request.   I left it as a separate field that is returned as part of the PUT request.  Please let me know if this is what you had in mind or if I am out on the left field.

2023-05-29 22:55 UTC, nemesisdesign commented
Thanks for your effort @tspare, we improved upon your work and merged this in https://github.com/openwisp/openwisp-firmware-upgrader/pull/231.

2023-05-29 22:55 UTC, closed without merging

2023-05-30 00:43 UTC, tspare commented
You are welcome.  Glad I could help.



On Mon, May 29, 2023 at 6:56 PM Federico Capoano ***@***.***>
wrote:

> Thanks for your effort @tspare <https://github.com/tspare>, we improved
> upon your work and merged this in #231
> <https://github.com/openwisp/openwisp-firmware-upgrader/pull/231>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwisp/openwisp-firmware-upgrader/pull/229#issuecomment-1567577259>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIG4NL5BEMRFRU7ANADC7SDXIUSQHANCNFSM6AAAAAAWTICPT4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>