[docs] Improved development installation instructions order
openwisp/openwisp-firmware-upgrader pull request #278
Opened 2024-11-09 19:15 UTC by praptisharma28

## Checklist

- [ ] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [ ] I have manually tested the changes proposed in this pull request.
- [ ] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [ ] I have updated the documentation.

## Description of Changes

The changes make the installation process more straightforward by:
1. Showing the big picture (directory structure) before details
2. Ensuring proper package isolation through correct virtualenv setup
3. Following Python best practices for development environments

2024-11-11 07:57 UTC, pandafy requested changes
@praptisharma28 I would just make the instructions consistent with other modules. 

You can use the [openwisp-controller](https://openwisp.io/docs/dev/controller/developer/installation.html#installing-for-development) for reference. 

https://github.com/openwisp/openwisp-controller/blob/master/docs/developer/installation.rst

2024-11-12 07:09 UTC, praptisharma28 commented on docs/developer/installation.rst
> +    └── openwisp-firmware-upgrader/   # Cloned repository
Is not this needed then?

2024-11-12 09:57 UTC, pandafy commented on docs/developer/installation.rst
> +    └── openwisp-firmware-upgrader/   # Cloned repository
Yes, this is not needed.

2024-11-13 17:16 UTC, nemesifier commented
This PR has overwritten a branch which we use for storing images and GIFs shown in the docs and website.
Please do not overwrite the `docs` branch. I am closing this PR so we can restore the original content. Please open a PR against master.

2024-11-13 17:16 UTC, closed without merging